version: '3'
services:
  routeapi:
    image: 127.0.0.1:5000/routeapi
    hostname: "routeapi"
    ports:
      - "5009:80"
    networks:
      - microservicenetwork

networks:
  microservicenetwork:
    external: true